# .eas/workflows/android-build-flow.yaml

name: Android Build (master)

on:
  push:
    branches:
      - master

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production